// pure redux-action types
export default {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    LOAD_PROFILE_REQUEST: 'LOAD_PROFILE_REQUEST',
    LOAD_PROFILE_ERROR: 'LOAD_PROFILE_ERROR',
    LOAD_PROFILE_SUCCESS: 'LOAD_PROFILE_SUCCESS',
    LOAD_PROFILE_FORM_REQUEST: 'LOAD_PROFILE_FORM_REQUEST',
    LOAD_PROFILE_FORM_SUCCESS: 'LOAD_PROFILE_FORM_SUCCESS',
    LOAD_PROFILE_FORM_ERROR: 'LOAD_PROFILE_FORM_ERROR',

    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',

    SEND_VERIFICATION_ERROR: 'SEND_VERIFICATION_ERROR',
    SEND_VERIFICATION_SUCCESS: 'SEND_VERIFICATION_SUCCESS',
    SEND_VERIFICATION_REQUEST: 'SEND_VERIFICATION_REQUEST',

    LOAD_CONFIGURATION_REQUEST: 'LOAD_CONFIGURATION_REQUEST',
    LOAD_CONFIGURATION_ERROR: 'LOAD_CONFIGURATION_ERROR',
    LOAD_CONFIGURATION_SUCCESS: 'LOAD_CONFIGURATION_SUCCESS',

    UPDATE_CONFIGURATION_REQUEST: 'UPDATE_CONFIGURATION_REQUEST',
    UPDATE_CONFIGURATION_ERROR: 'UPDATE_CONFIGURATION_ERROR',
    UPDATE_CONFIGURATION_SUCCESS: 'UPDATE_CONFIGURATION_SUCCESS',

    LOAD_CONFIGURATION_FORM_REQUEST: 'LOAD_CONFIGURATION_FORM_REQUEST',
    LOAD_CONFIGURATION_FORM_SUCCESS: 'LOAD_CONFIGURATION_FORM_SUCCESS',
    LOAD_CONFIGURATION_FORM_ERROR: 'LOAD_CONFIGURATION_FORM_ERROR',

    ADMIN_LOAD_MODELS_REQUEST: 'ADMIN_LOAD_MODELS_REQUEST',
    ADMIN_LOAD_MODELS_SUCCESS: 'ADMIN_LOAD_MODELS_SUCCESS',
    ADMIN_LOAD_MODELS_FAILURE: 'ADMIN_LOAD_MODELS_FAILURE',
    ADMIN_LOAD_MODEL_REQUEST: 'ADMIN_LOAD_MODEL_REQUEST',
    ADMIN_LOAD_MODEL_SUCCESS: 'ADMIN_LOAD_MODEL_SUCCESS',
    ADMIN_LOAD_MODEL_FAILURE: 'ADMIN_LOAD_MODEL_FAILURE'
};
