const SUCCESS = 'SUCCESS';
const DEPENDENCY_MISSING_IN_PACKAGE_JSON = 'DEPENDENCY_MISSING_IN_PACKAGE_JSON';
const NOT_TROVE_IMPORT = 'NOT_TROVE_IMPORT';
const UNNECESSARY_PACKAGE_DEPENDENCY = 'UNNECESSARY_PACKAGE_DEPENDENCY';

module.exports = {
  SUCCESS,
  DEPENDENCY_MISSING_IN_PACKAGE_JSON,
  NOT_TROVE_IMPORT,
  UNNECESSARY_PACKAGE_DEPENDENCY,
};
